### PR TITLE
Fix installing Gatekeeper when operator is deployed via OLM

### LINKED ISSUE #93: gatekeeper operator failed to deploy gatekeeper on OLM with error
```
2020-12-17T14:04:04.046Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "operator.gatekeeper.sh", "reconcilerKind": "Gatekeeper", "controller": "gatekeeper", "name": "gatekeeper", "namespace": "", "error": "Unable to deploy Gatekeeper resources: Error attempting to get resource /gatekeeper-webhook-server-cert: an empty namespace may not be set when a resource name is provided", "errorVerbose": "an empty namespace may not be set when a resource name is provided\nError attempting to get resource /gatekeeper-webhook-server-cert\ngithub.com/gatekeeper/gatekeeper-operator/controllers.(*GatekeeperReconciler).updateOrCreateResource\n\t/workspace/controllers/gatekeeper_controller.go:258\ngithub.com/gatekeeper/gatekeeper-operator/controllers.(*GatekeeperReconciler).deployGatekeeperResources\n\t/workspace/controllers/gatekeeper_controller.go:195\ngithub.com/gatekeeper/gatekeeper-operator/controllers.(*GatekeeperReconciler).Reconcile\n\t/workspace/controllers/gatekeeper_controller.go:156\nsigs.k8s.io/controlle...
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
```

### PR DESCRIPTION
**Pull request by font**
This adds the ability to use a default canonical namespace to install Gatekeeper when running on OpenShift, or default to using the same namespace as the operator on vanilla Kubernetes. As a result, the `WATCH_NAMESPACE` feature has been completely removed as this cluster scoped operator does not currently have a need for it.

Closes #93

### CODE REVIEW

File: pkg/util/namespace.go [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+	"io/ioutil"
+	"os"
+	"strings"
+
+	"github.com/pkg/errors"
+)
+
+var (
+	DefaultGatekeeperNamespace          = "gatekeeper-system"
+	DefaultOpenShiftGatekeeperNamespace = "openshift-gatekeeper-system"
```
Comment (ycao56) [inline pkg/util/namespace.go:27]: any technical reason why on openshift the default is `openshift-gatekeeper-system`?

Comment (ycao56) [reply pkg/util/namespace.go:27]: Is there a way to override this value `gatekeeper-system` on openshift?

Comment (ycao56) [reply pkg/util/namespace.go:27]: I would prefer to let openshift behave the same as vanilla k8s and provide the option to allow user specify which namespace to install gatekeeper through gatekeeper CR. This should work the same no matter it is openshift or vanilla k8s.

Comment (font) [reply pkg/util/namespace.go:27]: We could use any name we'd like here, but it has to be decided at compile time until #87 is resolved at least (I don't think resolving that issue is trivial until CRDs have built-in support for immuable fields). Whatever name we pick, it needs to be a canonical namespace to install Gatekeeper on OpenShift as I believe a cluster-scoped operator will land in `openshift-operators` by default, and we don't want to pollute that namespace unnecessarily. I opted to prefix `openshift-` to the normal default GK namespace as is typically the convention to indicate a reserved namespace, but there may be other things we need to do to officially reserve it.

On Kubernetes we default to using the same namespace the operator is running in. If we can remove the limitation that the operator will be installed to `openshift-operators`, then we can choose the same behavior as vanilla K8s. I'm open to other suggestions or ideas!

Comment (ycao56) [reply pkg/util/namespace.go:27]: ok. I was not aware of that on openshift the cluster-scoped operator will land in `openshift-operators`. With latest `bundle-index` image in `quay.io/gatekeeper`, I was able to create catalogsource, operatorgroup, subscription in `gatekeeper-system` ns and then the operator was deployed to `gatekeeper-system` ns. I guess it goes to `gatekeeper-system` ns because it was deployed by the custom catalog source not from ocp catalog.

Comment (ycao56) [reply pkg/util/namespace.go:27]: I think we can still go with field in CRD approach even the field is not `readOnly`. I expect if the user decides to update the namespace field, the gatekeeper will be uninstalled and reinstalled in the new namespace by the operator.

Comment (ycao56) [reply pkg/util/namespace.go:27]: I think this PR is good to go. We can discuss the CRD enhancement in issue #87

**Review by ycao56 — APPROVED** [review]

File: pkg/util/namespace.go (hunk 1 above)
Comment (ycao56) [reply pkg/util/namespace.go:27]: FYI, I just did some testing. I found that the operator would be installed in the namespace where subscription was created. e.g. catalog source in `openshift-marketplace`, subscription in `gatekeeper-system`, then operator was created in `gatekeeper-system`.
Not sure if it would work the same for ocp catalog, will have to test once it is published.

Comment (font) [reply pkg/util/namespace.go:27]: > I think we can still go with field in CRD approach even the field is not `readOnly`. I expect if the user decides to update the namespace field, the gatekeeper will be uninstalled and reinstalled in the new namespace by the operator. Maybe we can just document it for now to warn user the expected behavior.

I had also thought about doing that, but convinced myself against it because it seemed like a rather dangerous operation and possibly unintended from the user. Whereas making the field immutable would guarantee the user performs the intended delete and create action. If we agree to document it well with the plan to make that field immutable in the future, I could be amenable to this approach.

Comment (font) [reply pkg/util/namespace.go:27]: > FYI, I just did some testing. I found that the operator would be installed in the namespace where subscription was created. e.g. catalog source in `openshift-marketplace`, subscription in `gatekeeper-system`, then operator was created in `gatekeeper-system`. if subscription was in `openshift-operators`, then operator was created in `openshift-operators`.
> Not sure if it would work the same for ocp catalog, will have to test once it is published.

Correct, it is driven by the namespace of the subscription. The thing is the `openshift-operators` ns is how it's officially documented (https://docs.openshift.com/container-platform/4.6/operators/admin/olm-adding-operators-to-cluster.html) . It may still be configurable, but I'm not entirely sure if it can be done from the console.

**Comment by ycao56** [comment]
I think we should still consider making the default gatekeeper namespace on openshift gatekeeper-system because this is the namespace gatekeeper users familiar with. openshift-gatekeeper-system might be confusing.

**Comment by font** [comment]
> I think we should still consider making the default gatekeeper namespace on openshift gatekeeper-system because this is the namespace gatekeeper users familiar with. openshift-gatekeeper-system might be confusing.

I'm happy to make the change if we think this would be the best approach. Examples like OpenShift Pipelines (Tekton) using `openshift-pipelines` as the namespace on OCP, and `tekton-pipelines` on Kubernetes, convinced me to go with this option. But I don't have a strong opinion either way, aside from what I believe is the general convention that a canonical namespace should likely be a reserved namespace i.e. `openshift-` prefix.
